name: Autotag and Release Action
description: Automatically create tags and releases for your project.
author: pantheon-systems
branding:
  icon: tag
  color: yellow
inputs:
  gh-token:
    description: GitHub token with repo access
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Tag & Release
      shell: bash
      run: sh ${{ github.action_path }}/src/tag-release.sh
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}