name: Autotag and Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
      - name: Tag & Release
        uses: ./
        with:
          push-major-version-branch: true